### ISSUE TITLE
ScopedModelDescendant with Drawer and Navigator => model null

### ISSUE THREAD

**Issue by LarsKrogJensen** [brianegan/scoped_model#10]
I have a super simple scenario where a ScopedModelDescendant's builder always has a null model.

Scenario is that I want to change app theme from a settings page, I navigate to the settings page via Navigator.of(ctx).push(SettingsPage).

The settings page has a ScopedModelDescendant to read/update current theme, but model is always null.

The ScopedModel is wrapping the main app. 

Reproducer:
https://github.com/LarsKrogJensen/scoped_model

**Comment by brianegan** [comment]
Yah, this is sort of a weird thing with Dart. If you move the `Model` into a separate file and import it, all should be good.

**Comment by LarsKrogJensen** [comment]
Many thanks, that did the trick.

Any ideas or references to what is causing this, would be good to have deeper understanding on dart/flutter gotchas.

**Comment by brianegan** [comment]
Hrm, I actually don't. I feel like it might be a good idea to raise this issue on the Dart SDK github repo, however -- I get a lot of bug reports that come down to this issue, and this is one of the first things I check these days.
