### ISSUE TITLE
How to use load and persist json data in scoped model

### ISSUE THREAD

**Issue by pebreo** [brianegan/scoped_model#11]
I am trying to load json data using the scoped model like this:

```dart
import 'package:scoped_model/scoped_model.dart';
import 'package:flutter/services.dart' show rootBundle;

class MyModel extends Model {
  Map _jsonData;

  Future MyModel() async {
    // this won't work 
    String json =  await rootBundle.loadString('assets/words5.json');
     this._jsonData = json.decode(jsonString);
  }
  Map get jsonData => _jsonData;
}

```
After doing some research on stackoverflow, it was suggested I do something like this:

```dart
class MyModel extends Model {
  Map _jsonData;
  Future _doneFuture;

   MyModel()  {
      _doneFuture = _init();
   }

  Future _init() async {
    print('init');
    String jsonString = await _loadJsonFile();
    this._jsonData = json.decode(jsonString); 
  }

  Map get jsonData => _jsonData;
  Future get initializationDone => _doneFuture;

  Future<String> _loadJsonFile() async {
    return await rootBundle.loadString('assets/words.json');
  }

}

Future main() async {
 var c = new MyModel();
 await c.initializationDone;
 print('done');
  Widget app = new ScopedModel<CounterModel>(
 //.. 
)
}
```
Note that `rootBundle` returns a Future and that is, as far as I know, the only way to load files in Flutter.

I am running the newest Flutter and Dart 2 (`Channel master, v0.3.1-pre.15, on Mac OS X 10.12.6 16G29, locale en-US`) . Any idea how to load json data into my scoped model in Flutter?

**Comment by brianegan** [comment]
Hey there! Sure thing, happy to help. Yep, most apis that load data asynchronously will return a `Future` or a `Stream` of data. As far as loading data, using `rootBundle` looks good. However, rather than listening to the when the `Future` completes, I'd recommend listening to the `Model` and notifying the listeners (`ScopedModelDescendant` Widgets) when the state of the model changes.

```dart
class MyModel extends Model {
  bool _isLoading = true;
  bool get isLoading => _isLoading;

  Map _jsonData;
  Map get jsonData => _jsonData;

  Future loadData() async {
    // Set our model to loading
    _isLoading = true;
    // Notify Widgets listening to the model that it is now loading and they should 
    // show a loading spinner
    notifyListeners();

    // Load the data
    _jsonData = json.decode(await rootBundle.loadString('assets/words.json'));

    // Set loading to false now that the data is loaded
    _isLoading = false;

    // Once again, notify the Widgets listening to this model that it is done loading
    // and data is available for consumption
    notifyListeners();
  }
}

void main() {
  var model = new MyModel();
  model.loadData(); // Kick off the data loading as soon as the app starts

  Widget app = new ScopedModel<CounterModel>(
  // create a ScopedModelDescendant that listens to the isLoading boolean. 
  // If it's loading, show a spinner. If it is not loading, use the jsonData to build the UI.
)
```

**Comment by pebreo** [comment]
Thanks for the quick reply. I'll have to try it out.

**Comment by brianegan** [comment]
Heya @pebreo -- did this work for ya? Would like to close this out if so!

**Comment by pebreo** [comment]
It worked! Sorry for late reply.

**Comment by maheshkumar2150** [comment]
Is it possible to use scoped model with future builder?

**Comment by brianegan** [comment]
@maheshkumar2150 ScopedModel is a `Listenable`, it is not a Future. You can always have methods that return `Future<SomeData>` as well, but I'm not sure I'd personally use ScopedModel in that way.

Why? If you return a `Future<SomeData>` and another, unrelated component needs that same data from the model, they'd need to call `loadData` as well instead of just reading the already downloaded data from the Model.

**Comment by msw333** [comment]
Brian, can you elaborate on that? Thinking about integrating ScopeModel for my chat app. If I am now getting data via Firebaseanimatedlist (chat itself, Firebase Real Time Database), Streambuilder (overview of all chats, Firestore), Futurebuilder (Algolia search) - (3 screens) - does it make sense to use ScopeModel at all? Thought about integrating Firebase / Firestore into the model. How would you structure such an app with ScopeModel? Thought about ScopeModel for distributing user data (but this also needs to connect to Firebase via Futurebuilder)?

Grüße nach Berlin ;-)

**Comment by ollydixon** [comment]
This a great! As a note ```Future loadData()``` you could have synchronous to avoid ```_isLoading``` since loading JSON from a file is super fast on mobile (Users won't notice at the start of the app)
