### ISSUE TITLE
BuildContext InheritedWidget becomes null within a ScopedModel return object

### ISSUE THREAD

**Issue by datureezy** [brianegan/scoped_model#20]
Hello Brian,

I wanted to run this by you and see what you think.

I have an app where the MaterialApp which is wrapped by a ScopedModel<T> and it's working perfectly 👍 

I'm following this article to [Create build environments in Flutter](https://flutter.rocks/2018/03/02/separating-build-environments-part-one/).

I've tested the code in a guinea pig flutter app and the code works fine. I'm running print statements of the inherited widget of AppConfig when initialized and the values are valid. But when the Material App is wrapped by a scoped model, the BuildContext objects within the scoped model have no idea of the Inherited Widget of AppConfig. The build contexts in the scoped model are completely different from the build contexts in the AppConfig Inherited Widget.

I'm not sure if this is a bug where ScopedModels aren't taking into account of the inherited widgets, or if there is some sort of call that has to be made in the ScopedModel files to abide by the inherited widget updating the application's BuildContext.

If you can shed any light on this, it'll be much appreciated. Thanks, Brian.

**Comment by datureezy** [comment]
Brian,

Thank you for the quick response. I've tried again with this wrapping of my widgets to access the proper context but I've still come up short.

I will detail my code below...

---
**I have an AppConfig class that will contain an API URL that will differ on each build. From my knowledge, creating this inherited widget subclass is supposed to allow me to reach in and get the .apiURL string value after using the static function; AppConfig.of(context).apiURL**

class AppConfig extends InheritedWidget {
  final String apiURL;

  AppConfig({
    @required this.apiURL,
    @required Widget child,
  }) : super(child: child);

  static AppConfig of(BuildContext context) {
    return context.inheritFromWidgetOfExactType(AppConfig);
  }

  @override
  bool updateShouldNotify(InheritedWidget oldWidget) => false;
} 

---

**Here is my main_dev.dart file that I run when I test the app.**

void main() {
  var configuredApp = AppConfig(
    apiURL: 'https://dev-api.example.com/',
    buildIdentifier: BuildIdentifier.DEV,
    buildName: 'Development',
    child: MyApp(),
  );

  runApp(configuredApp);
}

---

**Here is my lib/main.dart file with the routing AND the Scoped Model**

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _MyAppState();
  }
}

class _MyAppState extends State<MyApp> {
  final MainModel _model = MainModel();

  @override
  Widget build(BuildContext context) {
    return ScopedModel<MainModel>(
      child: MaterialApp(
        routes: {
          '/': (BuildContext context) => MainScreen(_model),
        },
        theme: getThemeData(context),
        title: 'My App',
      ),
      model: _model,
    );
  }
}

---

**This is where I'm having my context give me questionable behavior, where I'm unable to use the context to then use my AppConfig's static function on to fetch my build's API URL.**

class MainScreen extends StatefulWidget {
  final MainModel model;

  MainScreen(this.model);

  @override
  State<StatefulWidget> createState() {
    return _MainScreenState();
  }
}

**1. This way about it doesn't work...**

class _MainScreenState extends State<MainScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(AppConfig.of(context).apiURL), // The getter 'apiURL' was called on null, and the whole screen is a sea of red.
      ),
      body: _buildGridView(context),
    );
  }
}

**2. This new way wrapping the context in a new class widget doesn't work either.**

class _MainScreenState extends State<MainScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: BrowseTitle(),
      ),
      body: _buildGridView(context),
    );
  }
}

class BrowseTitle extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var appConfig = AppConfig.of(context);
    return Text(appConfig.apiURL); // The getter 'apiURL' was called on null, but only the app bar title widget comes out as a red box
  }
}

---

Thanks for taking a look at this, Brian.

**Comment by brianegan** [comment]
Hey there -- sorry about such a long delay :/ Was super busy in July then dropped the ball on this one.

Hrm, I'm not 100% sure what could be going wrong. As a test, I made the following example and it seems to work fine.

One other common problem: You need to ensure you're importing all files with their full package path, otherwise Dart can resolve the class incorrectly.

For example, in main, rather than doing an `import 'app_config.dart';` use `import 'package:my_app/app_config.dart';`. You can see other's who've run into this bug here: https://github.com/brianegan/scoped_model/issues/15 and the Issue for the Dart team here: https://github.com/dart-lang/sdk/issues/33076


```dart
import 'package:flutter/material.dart';
import 'package:scoped_model/scoped_model.dart';

class AppConfig extends InheritedWidget {
  final String apiURL;

  AppConfig({
    @required this.apiURL,
    @required Widget child,
  }) : super(child: child);

  static AppConfig of(BuildContext context) {
    return context.inheritFromWidgetOfExactType(AppConfig);
  }

  @override
  bool updateShouldNotify(InheritedWidget oldWidget) => false;
}

void main() {
  runApp(AppConfig(
    apiURL: 'hello',
    child: MyApp(
      model: CounterModel(),
    ),
  ));
}

class MyApp extends StatelessWidget {
  final CounterModel model;

  const MyApp({Key key, @required this.model}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // At the top level of our app, we'll, create a ScopedModel Widget. This
    // will provide the CounterModel to all children in the app that request it
    // using a ScopedModelDescendant.
    return ScopedModel<CounterModel>(
      model: model,
      child: MaterialApp(
        title: 'Scoped Model Demo',
        home: CounterHome('Scoped Model Demo'),
      ),
    );
  }
}

// Start by creating a class that has a counter and a method to increment it.
//
// Note: It must extend from Model.
class CounterModel extends Model {
  int _counter = 0;

  int get counter => _counter;

  void increment() {
    // First, increment the counter
    _counter++;

    // Then notify all the listeners.
    notifyListeners();
  }
}

class CounterHome extends StatelessWidget {
  final String title;

  CounterHome(this.title);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('You have pushed the button this many times:'),
            // Create a ScopedModelDescendant. This widget will get the
            // CounterModel from the nearest parent ScopedModel<CounterModel>.
            // It will hand that CounterModel to our builder method, and
            // rebuild any time the CounterModel changes (i.e. after we
            // `notifyListeners` in the Model).
            ScopedModelDescendant<CounterModel>(
              builder: (context, child, model) {
                return Text(
                  '${model.counter}, Api URL: ${AppConfig.of(context).apiURL}',
                );
              },
            ),
          ],
        ),
      ),
      // Use the ScopedModelDescendant again in order to use the increment
      // method from the CounterModel
      floatingActionButton: ScopedModelDescendant<CounterModel>(
        builder: (context, child, model) {
          return FloatingActionButton(
            onPressed: model.increment,
            tooltip: 'Increment',
            child: Icon(Icons.add),
          );
        },
      ),
    );
  }
}
```
