### ISSUE TITLE
Idiomatic way to define a reactive function?

### ISSUE THREAD

**Issue by bbhh** [brianegan/scoped_model#21]
First off, thank you so much for creating this awesome package, it works very nicely! It fits the paradigm I'm used to with MobX and JavaScript. But one feature of MobX for which I couldn't find a counterpart is https://mobx.js.org/refguide/reaction.html and https://mobx.js.org/refguide/autorun.html, which allows you to define a function that is automatically run whenever a value changes.

In my case, I'd like to execute a `Navigator.of(context).pushReplacementNamed('...')` once the value of my `model.isSignedIn` boolean changes to true. In other words, once the user signs in, I'd like to redirect them to a members-only page.

I couldn't find a built-in way to do this in scoped_model, so I tried using a [ValueNotifier](https://docs.flutter.io/flutter/foundation/ValueNotifier-class.html) but somehow I wasn't getting any notifications in my StatefulWidget. Another hacky way I was thinking of exploring was using a [Timer](https://docs.flutter.io/flutter/dart-async/Timer-class.html) to keep checking to see if `model.isSignedIn` changes, but is there a better way?

Thank you!

**Comment by brianegan** [comment]
Hey there -- have you tried using using the `addListener` method? You can do something like this (kinda pseudo-code, need to set this up in the appropriate places:

```dart
final model = ModelFinder<MyModel>().of(context);
void modelListener() {
  if (model.isSignedIn) {
    Navigator.of(context).pushReplacement(...)
  }
}

// Start listening
model.addListener(modelListener);

// Stop Listening 
model.removeListener(modelListener);
```

**Comment by bbhh** [comment]
Great, thank you, Brian! I should've looked into the scoped_model code more closely to realize there was already listener capability inside. It works nicely, thank you!
