### ISSUE TITLE
Dart 2 Support

### ISSUE THREAD

**Issue by csjames** [brianegan/scoped_model#26]
It would seem scoped_model targets Dart SDK < 2.0.0, which means it will begin to cause compilation issues for people as they upgrade their projects to dart 2

**Comment by alejogamboa** [comment]
Same just happen to me right now.

please help!!!

**Comment by csjames** [comment]
For now you can stick --no-preview-dart-2 onto the end of your flutter run commands, and maybe git checkout tag/v0.5.8 (or somewhere around that). Should get you up and running whilst you are waiting.

**Comment by brianegan** [comment]
Fixed as part of `0.3.0`. Enjoy!
