### ISSUE TITLE
State with objects or lists

### ISSUE THREAD

**Issue by leisim** [brianegan/scoped_model#28]
Hi,

I like the idea of scoped model but all the examples only use primitive states. How can I use a list of objects in the model and update a single property of a single element of that list?

```dart
class Dog {
  String name;
}

class MyModel extends Model {
  List<Dog> _dogs;

  List<Dog> get dogs => _dogs;

  //How can I change the name of a specific dog in the list?
}
```

I could add a `changeName(index, newName)` method but how can I do that if the objects are more complex and have 20+ properties? Do I have to create a `changeProperty()` method for every property?

**Comment by brianegan** [comment]
Hey there -- In that case, rather than taking in a single property, I'll take in a completely new `Dog` object and replace the current index with the new `Dog` object.

Would look something like this:

```
class Dog {
  final String name;

  Dog(this.name);

  // Could add ability to create a new object with all properties
  Dog copyWith(String newName) {
    return Dog(newName ?? name); // If newName is null, use the current name;
  }
}

class MyModel extends Model {
  final List<Dog> _dogs;

  MyModel(List<Dog> initialDogs) : _dogs = initialDogs;

  List<Dog> get dogs => _dogs;

  void updateDog(int index, Dog dog) {
    _dogs[index] = dog;
    notifyListeners();
  }
}

// Usage:
final model = MyModel([Dog('Fido')]);

model.updateDog(0, model.dog[0].copyWith('Rex'));
```

**Comment by leisim** [comment]
Thank you! This really helps me 👍
