### ISSUE TITLE
Best practice on routing

### ISSUE THREAD

**Issue by paqio** [brianegan/scoped_model#31]
Is there a way to retain the scoped model when routing on logically a child route?

**Comment by brianegan** [comment]
Hey there -- in this case, you have two options:

  1. Provide the `ScopedModel` above the `MaterialApp` Widget. It will then be available to all Widgets you navigate to.
  2. If you only want to create the `ScopedModel` when the parent screen is created, you could pass the `Model` itself to the child Screen, which could then wrap the model in a new `ScopedModel` Widget that would only be accessible to that screen.
