### ISSUE TITLE
Interact with model outside the widget.

### ISSUE THREAD

**Issue by vmwsree** [brianegan/scoped_model#32]
I wanted to interact with the model when the animations are over , is there any way to have such interactions with scoped model
```
 var obj = new CounterModel();
  @override
  void initState() {
    super.initState();

    controller = new AnimationController(
        vsync: this, duration: new Duration(milliseconds: 3000));
    animation = new CurvedAnimation(parent: controller, curve: Curves.easeIn);
    animation.addListener(() {
      this.setState(() {


      });
    });
    animation.addStatusListener((AnimationStatus status) {
    if(status==AnimationStatus.completed){
     print("BELOW ISTHE CODE");
     model.increment(widget.widthRatio);

    }
    });
    controller.forward();

  }
```

**Comment by lishuhao** [comment]
+1

**Comment by lishuhao** [comment]
Finds a [Model] provided by a [ScopedModel] Widget.

 Generally, you'll use a [ScopedModelDescendant] to access a model in the
 Widget tree and rebuild when the model changes. However, if you would to
 access the model directly, you can use this function instead!

 ### Example

 ```
 final model = ScopedModel.of<CounterModel>();
 ```

 If you find yourself accessing your Model multiple times in this way, you
 could also consider adding a convenience method to your own Models.

 ### Model Example

 ```
 class CounterModel extends Model {
   static CounterModel of(BuildContext context) =>
       ScopedModel.of<CounterModel>(context);
 }
```
```
 // Usage
 final model = CounterModel.of(context);
 ```

[doc](https://github.com/brianegan/scoped_model/blob/3573343cb68b3e62d168b567ca8511cad71a98fb/lib/scoped_model.dart#L120)
