### ISSUE TITLE
I get an error when mixin 2 models to a main model

### ISSUE THREAD

**Issue by ChristBKK** [brianegan/scoped_model#35]
compiler message: lib/scoped-models/main.dart:6:17: Error: The type 'ProductsModel' can't be mixed in.

compiler message: class MainModel extends Model with UserModel, ProductsModel {}

compiler message:                 ^

compiler message: lib/scoped-models/main.dart:6:47: Error: Type 'ProductsModel' not found.

compiler message: class MainModel extends Model with UserModel, ProductsModel {}

compiler message:                                               ^

compiler message: lib/scoped-models/main.dart:1: Error: The superclass, '_MainModel&Model&UserModel&ProductsModel', has no unnamed constructor that takes no arguments.

-----

✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G2307, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.2)
[✓] Connected devices (1 available)

**Comment by passsy** [comment]
Can you post some code? You can't mixin a Model because to mixin a class, it has to extend `Object`.

**Comment by passsy** [comment]
I don't get why you need the `MainModel` at all. Isn't it enough to nest the models in each other?

```dart
new ScopedModel<UserModel>(
  model: new UserModel(),
  child: new ScopedModel<PostsModel>(
    model: new PostsModel(),
    child: myApp,
  ),
);

```

**Comment by ChristBKK** [comment]
Thanks will test this out!

**Comment by tomosullivan8** [comment]
Although you don't need the MainModel it might help if you wanted to add more models in the future? I think the following should work. Try and change the class for mixin and extends to on in the models that aren't Main Model. 

Main Model

```
import 'package:scoped_model/scoped_model.dart';

import './posts.dart';
import './user.dart';

class MainModel extends Model with UserModel, PostsModel {}
```

Posts Model

```
import 'package:scoped_model/scoped_model.dart';

import '../models/post.dart';

mixin PostsModel on Model {
  List<Post> _posts = [];

  List<Post> get posts {
    return List.from(_posts);
  }

  void addPost(Post product) {
    _posts.add(product);
  }

  void updatePost(int index, Post product) {
    _posts[index] = product;
  }

  void deletePost(int index) {
    _posts.removeAt(index);
  }
}

```
User Model

```
import 'package:scoped_model/scoped_model.dart';

import '../models/user.dart';

mixin UserModel on Model {
  User _authenticatedUser;

  void login(String email, String password) {
    _authenticatedUser = User(id: 'xxxxx', email: email, password: password);
  }
}
```

**Comment by nemoryoliver** [comment]
tried yours @tomosullivan8  but getting this error `flutter: Another exception was thrown: Error: Could not find the correct ScopedModel.`

**Comment by akhilasuraj** [comment]
https://medium.com/@amandeepkochhar/flutter-dart-the-class-cant-be-used-as-a-mixin-because-it-extends-a-class-other-than-object-a53eb5f214b0

here is olso some solutions that worked for me..

**Comment by Pman143** [comment]
1. mixin ProductModel on Model {}
2. mixin UserModel on Model {}
3. class MainModel extends Model with UserModel, ProductModel {}

Try out this. It worked for me.
