### ISSUE TITLE
Difference between ScopedModel and InheritedModel?

### ISSUE THREAD

**Issue by RNMBuser** [brianegan/scoped_model#37]
Dear Brian, Could you please tell me what's the difference between the two? I want to build an app that has multiple (approx 8) models, and listen to specific model(s). I also wish to have some way to use imperative API, so that, for example, a button press could raise a notification or the like.

I will be really glad to know which of the two you think I should use.

Also: do ScopedModel and InheritedModel work well with built_value?

**Comment by brianegan** [comment]
Hey there -- sorry my friend, somehow missed this one! 

Overall, I think scoped_model might not be necessary, and InheritedWidget is often enough (this is really just a simple wrapper around the Listenable and InheritedWidget classes). 

That said, I think `ScopedModel` can work really nicely if you want an imperative API. For example, you can wrap your Model's fields in Getters and Setters like so:

```dart
class CounterModel extends Model {
  // Private count that
  int _count = 0;

  int get count => _count;

  set count(int newCount) {
    _count = newCount;
    notifyListeners();
  }
}
```

After providing this small amount of code, you can now update your model imperatively, and the scoped model will take care of notifying any components that are listening!

```dart
final counter = CounterModel();

// Print the latest count whenever the model changes
counter.addListener(() { print(counter.count); });

counter.count = 1; // prints 1, because the setter will notify Listeners
```

Overall, I think this is a really nice / simple pattern if you like the imperative approach.

**Comment by RNMBuser** [comment]
Thanks a lot!

I have another question, please: Suppose I have an AppModel that is composed of 3 classes:
user: (username, token, etc)
cart: (items list)
wishlist: (items list)

Now for some reason I get logged out. I try to call the API from the cart, in order to update it, but get a message such as "access denied". How do I update the user model, and set the token to null? This is quite easy to do in Redux, but I have no idea how this can be done easily in other state-management systems.
