### ISSUE TITLE
Is ScopedModelDescendant necessary?

### ISSUE THREAD

**Issue by lizhuoyuan** [brianegan/scoped_model#38]
When I use the second way to find model, page does not refresh.
code:

```
Widget build(BuildContext context) {
    final appModel = ScopedModel.of<AppModel>(context);

    return Scaffold(
      body: Row(
        children: <Widget>[
          Switch(
              value: appModel.isNight,
              onChanged: (bool value) {
                print('value:$value');
                appModel.changeTheme(value);
              }),
        ],
      ),
    );
  }
```
 
![image](https://user-images.githubusercontent.com/15923901/46601398-7c9eb280-cb1f-11e8-926f-3efaf9249be0.png)

Switch has not changed，
but the first way is ok. 
If you can, I would like to see a complete example of the second method. Thank you!

**Comment by brianegan** [comment]
Hey there -- in this case, if you want to listen for changes you need to slightly change up that line:

`final appModel = ScopedModel.of<AppModel>(context, rebuildOnChange: true);`
