### ISSUE TITLE
Error: Could not find the correct ScopedModel.

### ISSUE THREAD

**Issue by jobinlaathan** [brianegan/scoped_model#42]
// this is my SignUp.dart file

import 'package:flutter/material.dart';
import 'dart:async';
import '../model/SignedUpList.dart';
import '../scoped_model/signupmodel.dart';
import 'package:scoped_model/scoped_model.dart';

class SignUp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return SignUpPage();
  }
}

class SignUpPage extends State<SignUp> {

  final myController = TextEditingController();

  FocusNode EmailFocusNode = new FocusNode();
  FocusNode PasswordFocusNode = new FocusNode();
  FocusNode ConfirmFocusNode = new FocusNode();

  List<SignedUpList> list=[];

  @override
  void dispose() {
    // Clean up the controller when the Widget is disposed
    myController.dispose();
    super.dispose();
  }

  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  final Map<String, dynamic> _formData = {
    'username': null,
    'email': null,
    'password': null,
  };

  Widget _buildusername() {
    return TextFormField(
      decoration: InputDecoration(
          focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(0.0)),
              borderSide: BorderSide(color: Colors.orange)),
          hintText: 'Username',
          border: OutlineInputBorder(
            borderRadius: BorderRadius.all(Radius.circular(0.0)),
          )),
      keyboardType: TextInputType.text,
      onEditingComplete: () {
        FocusScope.of(context).requestFocus(EmailFocusNode);
      },
      validator: (String value) {
        if (value.trim().length <= 0) {
          return 'Please enter a Username';
        }
      },
      onSaved: (String value) {
        _formData['username'] = value;
      },
    );
  }

  Widget _buildgradientbutton(double targetWidth) {
    return ScopedModelDescendant<signupmodel>(
        builder: (BuildContext context,Widget child,signupmodel model){
          return
            /*model.isLoading?
          Center(child: CircularProgressIndicator()):
          Container(
            width: targetWidth,
            height: 50.0,
            decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: <Color>[Colors.red, Colors.orange],
                ),
                boxShadow: [
                  BoxShadow(
                    color: Colors.grey[500],
                    offset: Offset(0.0, 1.5),
                    blurRadius: 1.5,
                  ),
                ]),
            child: Material(
              color: Colors.transparent,
              child: InkWell(
                  onTap: _submitForm(model.save_signup_form),
                  //onTap: this.onPressed,
                  child: Center(
                    child: Text(
                      'Sign Up',
                      style: TextStyle(color: Colors.white),
                    ),
                  )),
            ),
          )*/;
        }

    );

  }

  Widget _buildemail() {
    return TextFormField(
      decoration: InputDecoration(
          focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(0.0)),
              borderSide: BorderSide(color: Colors.orange)),
          hintText: 'E-Mail',
          border: OutlineInputBorder(
            borderRadius: BorderRadius.all(Radius.circular(0.0)),
          ),
          filled: true,
          fillColor: Colors.white),
      keyboardType: TextInputType.emailAddress,
      focusNode: EmailFocusNode,
      onEditingComplete: () {
        FocusScope.of(context).requestFocus(PasswordFocusNode);
      },
      validator: (String value) {
        if (value.isEmpty ||
            !RegExp(r"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?")
                .hasMatch(value)) {
          return 'Please enter a valid email';
        }
      },
      onSaved: (String value) {
        _formData['email'] = value;
      },
    );
  }

  Widget _buildpassword() {
    return TextFormField(
      controller: myController,
      decoration: InputDecoration(
        focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.all(Radius.circular(0.0)),
            borderSide: BorderSide(color: Colors.orange)),
        hintText: 'Password',
        border: OutlineInputBorder(
          borderRadius: BorderRadius.all(Radius.circular(0.0)),
        ),
      ),
      obscureText: true,
      focusNode: PasswordFocusNode,
      onEditingComplete: (){
        FocusScope.of(context).requestFocus(ConfirmFocusNode);
      },
      validator: (String value) {
        if (value.isEmpty || value.length < 6) {
          return 'Password invalid';
        }
      },
      onSaved: (String value) {
        _formData['password'] = value;
      },
    );
  }

  Widget _buildconfirmpassword() {
    return TextFormField(
      decoration: InputDecoration(
        focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.all(Radius.circular(0.0)),
            borderSide: BorderSide(color: Colors.orange)),
        hintText: 'Confirm Password',
        filled: true,
        fillColor: Colors.white,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.all(Radius.circular(0.0)),
        ),
      ),
      obscureText: true,
      focusNode: ConfirmFocusNode,
      onEditingComplete: (){

        _submitForm(signupmodel().save_signup_form);

        /* setState(() {
          _submitForm(signupmodel().save_signup_form);
          signupmodel().isLoading=true;
        });*/

        },
      validator: (String value) {
        if (value != myController.text) {
          print(value);
          return 'Passwords not matching';
        }
        //dispose();
      },
    );
  }

  _submitForm(Function save_signup_form) {

    if (!_formKey.currentState.validate()) {
      return;
    }
    _formKey.currentState.save();
    print(_formData);
    save_signup_form(_formData['username'],_formData['email'],_formData['password']).then((bool success) {
      if (success) {
        Navigator.pushReplacementNamed(context, '/');
      } else {
        showDialog(
            context: context,
            builder: (BuildContext context) {
              return AlertDialog(
                title: Text('Something went wrong'),
                content: Text('Please try again!'),
                actions: <Widget>[
                  FlatButton(
                    onPressed: () => Navigator.of(context).pop(),
                    child: Text('Okay'),
                  )
                ],
              );
            });
      }
    });
    //Navigator.pushReplacementNamed(context, '/Log_In');
  }

  void _loginpage() {
    Navigator.pushReplacementNamed(context, '/');
  }

  Future<bool> _backButtonpressed() async{

    Navigator.of(context).pop();

  }
  @override
  Widget build(BuildContext context) {
    // TODO: implement build

    final double deviceWidth = MediaQuery.of(context).size.width;
    final double targetWidth = deviceWidth > 550.0 ? 500.0 : deviceWidth * 0.95;
    return WillPopScope(
        onWillPop: _backButtonpressed,
        child:Scaffold(
      appBar: AppBar(
          backgroundColor: Colors.white,
          elevation: 0.0,
          title: Center(
            child: Text('Sign Up'),
          )),
      body: Container(
        decoration: BoxDecoration(color: Colors.white),
        padding: EdgeInsets.all(10.0),
        child: Center(
          child: SingleChildScrollView(
            child: Container(
              width: targetWidth,
              child: Form(
                key: _formKey,
                child: Column(
                  children: <Widget>[
                    _buildusername(),
                    _buildemail(),
                    _buildpassword(),
                    _buildconfirmpassword(),
                    SizedBox(
                      height: 10.0,
                    ),
                    _buildgradientbutton(targetWidth),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
      bottomNavigationBar: FlatButton(
          child: Text('Sign In'), onPressed: _loginpage),
    )
    );
  }
}

//this is myscopedmodel signupmodel

import 'package:scoped_model/scoped_model.dart';
import '../model/SignedUpList.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'dart:async';

class signupmodel extends Model{

  bool isLoading;
  List<SignedUpList> list=[];

  Future<bool> save_signup_form(String _username,String _email,String _password,) async{

    isLoading=true;
    notifyListeners();
    final Map<String, dynamic> _signupData = {
      'username': _username,
      'email': _email,
      'password':_password,
    };
    try {
      final http.Response response = await http.post(
          'https://sample-f765a.firebaseio.com/signuplist.json',
          body: json.encode(_signupData));

      if (response.statusCode != 200 && response.statusCode != 201) {
        isLoading = false;
        notifyListeners();
        return false;
      }
      final Map<String, dynamic> responseData = json.decode(response.body);
      print(responseData);
      isLoading = false;
      notifyListeners();
      return true;
      
    } catch (error) {
      isLoading = false;
      notifyListeners();
      return false;
    }
  }
}

**Comment by brianegan** [comment]
Hey there -- sorry, somehow missed this one :/

It looks like you're trying to use `ScopedModelDescendant` without providing the appropriate Type information. It needs to be: `ScopedModel<SignUpModel>` and `ScopedModelDescendant<SignUpModel>`.
