### ISSUE TITLE
navigate to new route from model

### ISSUE THREAD

**Issue by ronmany** [brianegan/scoped_model#43]
Is there a way to navigate to a new route from the model (not from the page widget)?

I need to navigate out of the screen on some logical condition (as oppose to user action)
Is there a way to do it directly from the model logic?

Currently I setup a flag in the model and use it to show a "finish" button to the user where the navigation happens (onPressed), but I would like to navigate without the user's interaction.

Thank you

**Comment by brianegan** [comment]
Hey there -- in this case, I think you have the right approach (setting a flag to know to navigate). However, rather than using that information to display a button, you can listen to the model yourself to perform the navigation.

You would need a StatefulWidget, and it would look something like this:

```dart
import 'package:flutter/material.dart';
import 'package:scoped_model/scoped_model.dart';

void main() {
  runApp(MyApp(
    model: NavigationModel(),
  ));
}

class MyApp extends StatelessWidget {
  final NavigationModel model;

  const MyApp({Key key, @required this.model}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ScopedModel<NavigationModel>(
      model: model,
      child: MaterialApp(
        title: 'Navigation Demo',
        home: LoginScreen('Login'),
      ),
    );
  }
}

class NavigationModel extends Model {
  bool _navigate = false;

  bool get navigate => _navigate;

  void onSubmit(String username, String password) {
    // perform some validation, call a backend, etc.
    // Then, if all that succeeds:
    _navigate = true;
    notifyListeners();
  }
}

class LoginScreen extends StatefulWidget {
  final String title;

  LoginScreen(this.title);

  @override
  LoginScreenState createState() {
    return new LoginScreenState();
  }
}

class LoginScreenState extends State<LoginScreen> {
  final emailController = TextEditingController();
  final passwordController = TextEditingController();

  // You cannot access the scoped model in the `initState` function because the
  // `context` variable has not been established. Therefore, you need to access
  // it in the `didChangeDependencies` method.
  //
  // Note: This function can be called several times, but adding the exact same
  // listener (the _navigationListener method) to the model will not result
  // in the function being called multiple times when the data changes.
  @override
  void didChangeDependencies() {
    ScopedModel.of<NavigationModel>(context).addListener(_navigationListener);
    super.didChangeDependencies();
  }

  @override
  void dispose() {
    // Make sure to clean up after ourselves by removing the listener!
    ScopedModel.of<NavigationModel>(context)
        .removeListener(_navigationListener);

    // Also dispose of the controllers...
    emailController.dispose();
    passwordController.dispose();
    super.dispose();
  }

  // This function will be run every time the model changes! We will use it to
  // check the navigate boolean. If it's set to true, we'll push a new screen!
  //
  // If not, we won't do anything.
  void _navigationListener() {
    if (ScopedModel.of<NavigationModel>(context).navigate) {
      // In this case, since it's a login Screen and we don't want the user to
      // go "Back" to it, we push a replacement
      Navigator.of(context).pushReplacement(
          MaterialPageRoute(builder: (context) => SecondScreen()));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: <Widget>[
          TextField(
            controller: emailController,
            decoration: InputDecoration(hintText: 'Email'),
          ),
          TextField(
            controller: passwordController,
            decoration: InputDecoration(hintText: 'Password'),
          ),
          RaisedButton(
            child: Text('Login'),
            onPressed: () => ScopedModel.of<NavigationModel>(context)
                .onSubmit(emailController.text, passwordController.text),
          )
        ],
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second Screen'),
      ),
      body: Center(
        child: Text('Logged in!'),
      ),
    );
  }
}
```

**Comment by ronmany** [comment]
Thank you for the detailed answer.
It is working beautifully...

**Comment by Disjes** [comment]
Hi, Sorry to get into an old issue, my listener is not called at all, is there something I could be doing wrong?

Here is the code:

**Model**

`class UserModel extends Model {
  UserModel(this._repository);
  final Repository _repository;

  bool _isLoading = false;
  User _user;

  User get user => _user;
  bool get isLoading => _isLoading;

  void loadUserData(String email) {
    _isLoading = true;
    notifyListeners();
    _repository.getUser(email).then((user) {
      _user = user;
      _isLoading = false;
      notifyListeners();
    });
  }

  static UserModel of(BuildContext context) => ScopedModel.of<UserModel>(context);

}`

**ScopedModel**

`class LoginApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    /*return MaterialApp(
      title: 'Login Challenge',
      theme: ThemeData(
        primarySwatch: Colors.deepPurple
      ),
      home: LoginPage(),
    );*/
    UserModel model = UserModel(Repository());
    return ScopedModel<UserModel>(
        model: model,
        child: MaterialApp(
          title: 'Seguros Continental',
          home: LoginPage(),
        ),
    );
  }
}`

`class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() {
    return _LoginPageState();
  }
}`

`class _LoginPageState extends State<LoginPage> {

  // f45d27
  // f5851f

  String _email;
  String _password;
  final UserModel model = UserModel(Repository());

  @override
  void initState() {
    SystemChrome.setEnabledSystemUIOverlays([]);
    super.initState();
    _email = "";
    _password = "";
  }

  @override
  Widget build(BuildContext context) {
//Lots of widgets..
    return ,
                    GestureDetector(
                      onTap: () {
                        if (model.user == null) {
                          model.loadUserData(_email);
                        }
                      },
                      child: ScopedModelDescendant<UserModel>(

                        builder: (context, child, model) {
                          if (model.user != null) {
                            _buildContent(model);
                          }
                          if (model.isLoading) {
                            return _buildLoading();
                          }
                          else {
                            return Container(
                              height: 45,
                              width: MediaQuery.of(context).size.width/1.2,
                              decoration: BoxDecoration(
                                  gradient: LinearGradient(
                                    colors: [
                                      Color(0xFFC2185B),
                                      Color(0xFF880E4F)
                                    ],
                                  ),
                                  borderRadius: BorderRadius.all(
                                      Radius.circular(50)
                                  )
                              ),
                              child: Center(
                                child: Text('Login'.toUpperCase(),
                                  style: TextStyle(
                                      color: Colors.white,
                                      fontWeight: FontWeight.bold
                                  ),
                                ),
       );
      }

    Widget _buildLoading() {
      return const Center(
        child: CircularProgressIndicator(),
      );
    }

    @override
    void didChangeDependencies() {
      ScopedModel.of<UserModel>(context).addListener(_navigationListener);
      super.didChangeDependencies();
    }

    @override
    void dispose() {
      // Make sure to clean up after ourselves by removing the listener!
      ScopedModel.of<UserModel>(context)
          .removeListener(_navigationListener);

      super.dispose();
    }

    void _navigationListener() {
      if (ScopedModel.of<UserModel>(context).user != null) {
        // In this case, since it's a login Screen and we don't want the user to
        // go "Back" to it, we push a replacement
        Navigator.push(
            context,
            MaterialPageRoute(
                builder: (context) => MyHome()));
      }
    }

  }`

Thanks a lot,

**Comment by xalikoutis** [comment]
Or a really dirty solution use a navigatorKey

Create a static key
`import 'package:flutter/widgets.dart';
class SfcKeys {
  static final navKey = new GlobalKey<NavigatorState>();
}`

and then in your model

```
final navigatorKey = SfcKeys.navKey;
navigatorKey.currentState
            ..push(MaterialPageRoute(
                builder: (context) => AlertWidget(
                      title: "Error",
                      message: error.message,
                      ok: "OK",
                    )));

```

**Comment by Kerolos9008** [comment]
sorry @xalikoutis but what is the idea exactly u still passed context in MaterialPageRoute where did u get that from in your model

**Comment by xalikoutis** [comment]
You dont pass it. It is just the context from currentState

**Comment by terebusk** [comment]
In my case the line in dispose method is causing an exception to be thrown, the application keeps running though.

`Looking up a deactivated widget's ancestor is unsafe. At this point the state of the widget's element tree is no longer stable. To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.`

It's gone when I comment it out.

The only difference I see that I'm doing is in _navigationListener I use
`Navigator.pushReplacementNamed(context, '/home');`
Instead of MaterialPage. Any way to fix that?

**Comment by Luktm** [comment]
My solution is instead of use` Navigator.pushReplacement` I use `Navigator.push().then((value) => Navigator.pop())`. I think this is not a right approach.
