### ISSUE TITLE
New Approach for using multiple model classes (former with)

### ISSUE THREAD

**Issue by ralph-fuechtenkort** [brianegan/scoped_model#44]
Hi and Good Afternoon,
first thanks for your work. For me its the best balanced approach for handling state in flutter :)
This is actually not an issue of the lib but after updating Flutter, using 'with" to have separate model files is not supported anymore, what would be the best way - from the architects side (you)) to accomplish that.
In more complex apps having all logic in one file seems not appropriate and me personally dont like the Repository approach so much.
Any help appreciated.
Greets from Manila

**Comment by edodso2** [comment]
I faced the same issue and had to change the syntax from:

class UserModel extends Model

to:

mixin UserModel on Model
