### ISSUE TITLE
Get previous state, when state is updated

### ISSUE THREAD

**Issue by khayalan-mathew** [brianegan/scoped_model#49]
Hey :)

So is there a way to get the previous state, when an update arrives.
My use case is starting an animation, so i have for example a loading variable in my LoginModel, but i only want to trigger the animation when loading changed from false to true.
Is there a way to do this?

Best regards,
Mathew

**Comment by brianegan** [comment]
Unfortunately that type of functionality isn't baked into Listenables.

To handle that case, you'll need to manually cache the previous value inside a `State` class.
