### ISSUE TITLE
Move to React Context naming

### ISSUE THREAD

**Issue by passsy** [brianegan/scoped_model#5]
React just published the [Context API](https://medium.com/dailyjs/reacts-%EF%B8%8F-new-context-api-70c9fe01596b) with the same features as scoped_model. I was thinking about changing the names of scoped_model to conform the React names (Which are pretty good).

`ScopedModel<AModel>` -> `ContextProvider<AModel>`
`ScopedModelDescendant<AModel>` -> `ContextConsumer<AModel>`

//cc @apwilson

**Comment by passsy** [comment]
We can agree that `scoped_model` and `InheritedWidget` are very close together. Especially because `scoped_model` uses `InheritedWidget` internally. I still think ScopedModel is a better equivalent to the Context API than `InheritedWidget` alone.

1. Models also have to call `setState` indirectly via `notifyListeners()` to send updates down the tree.
2. `InheritedWidget` alone has no equivalent to `ContextConsumer` like `scoped_model` has with `ScopedModelDescendant`. `InheritedWidget` implicitly registers a dependency when calling `inheritFromWidgetOfExactType` which is not as clear as in `scoped_model` or the Context API. Pretty hard for newcomers.


The distinction between BuildContext and `Context` could be a problem and the main reason we will not change the name. Although I've never seen somebody creating variables for `ScopedModel` or `ScopedModelDescendant` and name clashes with `BuildContext` will rarely happen.

```dart
// never seen something like this
var scopedModel = new ScopedModel(...)
var scopedModelDescendant = new ScopedModelDescendant(...)
```

What about this?

`ScopedModel<AModel>` -> `ModelProvider<AModel>`
`ScopedModelDescendant<AModel>` -> `ModelConsumer<AModel>`

**Comment by brianegan** [comment]
Yep, I think `ModelProvider` and `ModelConsumer` are good names and avoid calling too many things "Context"! I always found `ScopedModelDescendant` to be a mouthful and the name doesn't really describe what it does.

"I still think ScopedModel is a better equivalent to the Context API than InheritedWidget alone." -- From an API standpoint, I agree. From a functionality standpoint, I disagree. But don't think it's worth getting into a long debate. We each view it in a slightly different way :)

I've got a bit going on right now to support Dart 2, would you mind preparing a PR?

**Comment by passsy** [comment]
will do :)

**Comment by brianegan** [comment]
@passsy Yessss, thanks so much for all the help with this lib! <3

**Comment by passsy** [comment]
I'm undecided. Renaming `ScopedModel` to `ModelProvider` would completely vanish the name `ScopedModel` from this lib. Renaming `scoped_model` to something else would be the logical next step.

Only renaming `ScopedModelDescendant` to `(Scoped)ModelConsumer` is a tiny improvement. Without a `ModelProvider` it wouldn't reach the goal to match the naming with the Context API. 😩

Requires more thinking...

**Comment by brianegan** [comment]
Yah, I was thinking about that as well. Overall, I'm comfy with it if you are, but might not be worth it!? 

🤷‍♀️ 🤷‍♂️

**Comment by apwilson** [comment]
After reading this and some discussion with my team we also like a more natural language approach to naming like:

ScopedModel<AModel> =>  Provide<AModel>
ScopedModelDescendant<AModel> => BuildWith<AModel>

Thoughts on that style of naming?

**Comment by passsy** [comment]
I'm fine with `Provide` and `BuildWith`. Let's discuss renaming this project separately.

**Comment by brianegan** [comment]
I'm not the biggest fan of those names (since they're verbs instead of nouns), but I'm happy to defer to others who use this library more and what feels natural.

Please feel free to submit a PR and I can help review :)

**Comment by chimon2000** [comment]
Keeping with the theme of mirroring the redux naming patterns like alternatives [unistore](https://github.com/developit/unistore) and [react-waterfall](https://github.com/didierfranc/react-waterfall), it could be `Provider` and `Connector` similar to how flutter_redux has `StoreProvider` and `StoreConnector`

**Comment by brianegan** [comment]
Any more thoughts on this? Seemed like we got a lot of suggestions, but not sure if we landed on something. Happy to make this change, just need to know what names you'd like to use :)

**Comment by chimon2000** [comment]
I think the consensus seems to be Provide & BuildWith.

**Comment by brianegan** [comment]
Thanks @chimon2000! @apwilson @passsy -- What are your thoughts? Should I go forward with the change?

**Comment by brianegan** [comment]
Overall, we're discussing deprecating this package in favor of the `provider` package. That package uses the react naming conventions: `Provider` and `Consumer`. It offers all the functionality of scoped_model, but also allows you to pass down any kind of Value, not just a listenable! I'd recommend moving to that if you'd prefer the react naming conventions.
