### ISSUE TITLE
Missing docs on best way to instantiate the ScopeModel widget when you have multiple models

### ISSUE THREAD

**Issue by bbozo** [brianegan/scoped_model#54]
The "Listening to multiple Models in a build function" doesn't cover how to instantiate the app for the first time, ie there's no multi-model equivalent of:

```
class CounterApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // First, create a `ScopedModel` widget. This will provide 
    // the `model` to the children that request it. 
    return new ScopedModel<CounterModel>(
      model: new CounterModel(),
```

in the docs :-) Only solutions I found online boil down to creating a God object of all the model objects and then passing it to the main app widget in a `ScopedModel<God>` call (ie https://proandroiddev.com/you-might-not-need-redux-the-flutter-edition-9c11eba006d7, but also https://www.udemy.com/learn-flutter-dart-to-build-ios-android-apps/learn/v4/t/lecture/12309188?start=0 & others),

this is the only solution I found so far, I refuse to believe this is the truth (and it doesn't work with newer versions of Dart, you can't instantiate a mixin), so I'm hoping for some sage guidance from the Creators ^_^

**Comment by bbozo** [comment]
My take on it:

```
class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    Widget rv;
    
    rv = MaterialApp(
      // ....
    );

    rv = ScopedModel<UsersModel>(model: UsersModel(), child: rv);
    rv = ScopedModel<ProductsModel>(model: ProductsModel(), child: rv);

    return rv;
  }
```

**Comment by koudle** [comment]
I do it this way:
```
class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return ScopedModel<UsersModel>(
        model: UsersModel(),
        child: ScopedModel<ProductsModel>(
             model: ProductsModel(),
             child: MaterialApp(
                           // ....
                       ),
        ),
    );
  }
}
```

**Comment by bbozo** [comment]
@brianegan @koudle I'm glad you guys are on this because people out there are resorting to some really crazy shit such as combining all of the models via mixins into a GodModel object and stuff like that :scream: it's new technology, and the demography that's using it doesn't seem to come from a pool of people who understand these patterns and language constructs.

I'd guess that the nested approach won't scale well with a number of models that's typical for a well-developed app, how about an API that takes that into consideration? Something like

```
return ScopedModelContainer(
  models: <Model>[
    UsersModel(),
    ProductsModel(),
    ...
  ]
);
```

This goes well in hand with what seems to be the assumption - that each of the `ScopedModel` classes are singletons - not intended to exist more than one instance per application / or at least per `BuildContext context` instance.

-------------------------

A design suggestion.... Since the models are singleton instances anyway, there's nothing really that is gained from enforcing the singleton pattern, a registry based approach here may be better ie:

```
    ModelRegistry modelRegistry = ModelRegistry();

    modelRegistry.register('users', UsersModel(modelRegistry));
    rv = ScopedModel<UsersModel>(model: modelRegistry['users'], child: rv);

    modelRegistry.register('products', ProductsModel(modelRegistry));
    rv = ScopedModel<ProductsModel>(model: modelRegistry['products'], child: rv);
```

and then to fetch a model instance: `modelRegistry['users']`

because this allows you to assign a unique string to an instance of the `Model` and then you can allow for multiple instances of the same model class and this allows you to compose models and do things like:

```
model.register('users/local', UsersModel(localRepository));
model.register('users/oauth', UsersModel(oauthRepository));
```

I actually did this in my app to be able to fetch model instances from the models themselves, ie:

```
  User get currentUser => (modelRegistry['users'] as UsersModel).currentUser;
```

to be able to set `user_id` for products.

**Comment by bbozo** [comment]
Good points, thank you ^_^ I'll keep a particular eye on `providerscope`, btw should the example code for the delegator to `ScopedModel.of` in [Finding the model](https://github.com/brianegan/scoped_model#finding-the-model) use `rebuildOnChange: true` or have it available as a pass-through parameter?

**Comment by brianegan** [comment]
Hey all -- I think it makes sense to merge this package with the `provider` package when 2.0.0 is ready. Therefore, I'm going to hold off on adding this functionality to scoped model.

Please see the `provider` package for an alternative solution to this very problem!
