### ISSUE TITLE
Docs missing lines

### ISSUE THREAD

**Issue by dark-chocolate** [brianegan/scoped_model#56]
See the screenshot, it is missing lines in the docs. 
However, I know `rebuildOnChange` tells you whether the `ScopedModelDescendant`'s `builder()` method should get called when the model changes mentioned that we call `notifyListeners()` in the model. 

![image](https://user-images.githubusercontent.com/40364434/51236500-4aabb080-1998-11e9-8978-e5538f1ff0da.png)

**Comment by brianegan** [comment]
Thanks! I'll patch that up.
