### ISSUE TITLE
Make the model providers stateful to keep the state of the current model

### ISSUE THREAD

**Issue by MichaelPriebe** [brianegan/scoped_model#58]
Using a Model on a page with a text box, the model will reset because the keyboard rebuilds the app.

**Comment by xalikoutis** [comment]
Wow having the same problem. I am trying to port an app of mine from xamarin.forms to flutter and i am having problem with reinitializing the scopemodel every time keyboard is up.

**Comment by MichaelPriebe** [comment]
You can solve the issue yourself by making the models in a state.

If the provider passed the model to it's state it would have a similar effect. The model would technically be made again and the constructor would be called so any initialization stuff would be done over again and thrown away. So maybe just having a special PersistentScopedModel where the model is a builder and the provider builds the model in it's state and does not build it again.

**Comment by MichaelPriebe** [comment]
I'm not sure of an occasion you would WANT the Model to reset when the app is rebuilt, so maybe the provider should take a model builder by default.

**Comment by brianegan** [comment]
Hey all -- thanks for the feedback! Overall, I think we'll be deprecating this package in favor of the `provider` package. It offers very similar functionality out of the box with additional goodies like `StatefulProvider` that solves exactly this problem.

I'd suggest trying out the `provider` package + `StatefulProvider` to see if that works for ya!

**Comment by elforce001** [comment]
@brianegan Thanks for the heads-up! I have a question. Do we use the master branch or go for v2.0.0? 
Thanks.
