### ISSUE TITLE
actions  in AppBar is not updated when call notifyListeners

### ISSUE THREAD

**Issue by hasonguo** [brianegan/scoped_model#63]

**Comment by hasonguo** [comment]
when body changed,actions also changed together.but it was'nt. i wish to resolve it.pleas tell me how to resove it temporary.


`appBar: AppBar(
        title: Text(ScopedModelLocalizations.of(context).appTitle),
        actions: [
          FilterButton(isActive: _activeTab == AppTab.todos),
          ExtraActionsButton()
        ],
      ),`

**Comment by brianegan** [comment]
It sounds like you are not listening to the Model in the Widget tree! You can use a `ScopedModelDescendant` which will automatically listen to the Model and rebuild any time `notifyListeners` is called.

If these Widgets are not wrapped in that kind of Widget, they will not be automatically rebuilt when the model notifies.

**Comment by hasonguo** [comment]
> It sounds like you are not listening to the Model in the Widget tree! You can use a `ScopedModelDescendant` which will automatically listen to the Model and rebuild any time `notifyListeners` is called.
> 
> If these Widgets are not wrapped in that kind of Widget, they will not be automatically rebuilt when the model notifies.

Ok，thanks. I had resolved it.Scaffold was wrapped by ScopedModelDescendant so that appbar rebuild anytime when `notifyListeners` is called.But I have a question which whether affecting efficiency or not. All of widgets will be called when `notifyListeners` is called.
