### ISSUE TITLE
Should `notifyListeners` method be annotated @protected like in `ChangeNotifier`

### ISSUE THREAD

**Issue by yathit** [brianegan/scoped_model#7]
https://github.com/brianegan/scoped_model/blob/9a47bae546bb208d76cf5cd8e7c9d1bb17df59d5/lib/scoped_model.dart#L29

**Comment by brianegan** [comment]
Thanks for pointing that out! I'll take a look.

**Comment by brianegan** [comment]
Fixed as part of `0.3.0`!
