### ISSUE TITLE
ScopedModelDescendant for AppBar

### ISSUE THREAD

**Issue by carmas123** [brianegan/scoped_model#71]
Please can you add a custom ScopedModelDescendant to handle scoped models for AppBar

I've done a simple descendent class:

```
class ScopedPreferredSizeModelDescendant<T extends Model> extends ScopedModelDescendant<T> implements PreferredSizeWidget {
  ScopedPreferredSizeModelDescendant({
    @required ScopedModelDescendantBuilder<T> builder,
    Widget child,
    bool rebuildOnChange = true,
  }) : super(builder: builder, child: child, rebuildOnChange: rebuildOnChange);

  @override
  // TODO: implement preferredSize
  Size get preferredSize => null;
}
```

this can be useful to handle builder for appbar

**Comment by brianegan** [comment]
Does the entire AppBar need to be wrapped in a PreferredSizeWidget or would it make sense to wrap the individual Widgets you provide to the AppBar in a `ScopedModelDescendant`? E.g. wrap the `title` and `actions` instead of the entire `AppBar`?
