### ISSUE TITLE
accessing scoped model from helper class

### ISSUE THREAD

**Issue by jodymac** [brianegan/scoped_model#74]
I have scoped model working just fine from multiple locations in my app to update a status pane on my main page.  My problem is that I also run a cron job from a helper class, no build context, no widgets.  Is there a way I can call the scoped model to update the status pane with new results from the cron job.  The cron job can be set 24 hours to a week in advance.

**Comment by brianegan** [comment]
Is there any way you can pass the Model into the helper class when it's first created? You could even create the Model in the `main` function if it's around for the lifecycle of the app and then create the helper at that point as well by passing the model in at that point.

**Comment by jodymac** [comment]
Thanks Brian,

Passing the model worked perfectly!
