### ISSUE TITLE
Passing ScopedModel between screens

### ISSUE THREAD

**Issue by itelixgithub** [brianegan/scoped_model#77]
Can somebody pretty please show me the way of passing ScopedModel between screens ? I'd prefer not to wrap my whole application, but to pass it somehow...

What I want to achieve is to create ScopedModel object in my ScreenTabs Widget, then pass it to tab ScreenBook (1st descendant) and then my tab navigates to another screen ScreenBookDetails (2nd descendant) -thats where I'm getting Error: Could not find correct ScopedModel.

`
SCREEN TAB
...
```
class ScreenTabsState extends State<ScreenTabs> {
ModelTabs modelTabs = ModelTabs(); //new Model object
var screens = [new ScreenHome(),new ScreenBook(),];

@override
Widget build(BuildContext context) {
return ScopedModel<ModelTabs>(
model: modelTabs, 
child: Scaffold(...)
body: Builder (builder: (context) => Container(child:  
screens.elementAt(selectedIndex),)),
bottomNavigationBar: BottomNavigationBar(
currentIndex: selectedIndex,
items: [...],
onTap: onTabTapped,
),)...}`

```
`SCREEN BOOK //works fine
```
...
class ScreenBookState extends State<ScreenBook> {

@override
Widget build(BuildContext context) {
return new Scaffold(
body: ScopedModelDescendant<ModelTabs>(builder: (context, child, model) {
print(TAG + "model status:" +  model.status.toString());
return model.status == Status.LOADING ? MyCircularProgressIndicator() :         
Builder (builder: (context) => 
Card(...
child: InkWell(
onTap: (){
Navigator.of(context).pushNamed("/ScreenBookDetails");},))}}
```
`

`SCREEN BOOK DETAILS //error when printing
```
...
class ScreenBookDetailsState extends State<ScreenBookDetails>{

@override
Widget build(BuildContext context) {
return Scaffold(
body: ScopedModelDescendant<ModelTabs>(builder: (context, child, model) {
print(TAG + "scoped model status: " + model.status.toString()); //Error: Could not find the correct ScopedModel.
return model.status == Status.LOADING ? MyCircularProgressIndicator() :     Builder(builder: (context) => Column(...)
```
...
`

Thank you very much in advance - I'm new to this stuff but the whole idea of ScopedModel is amazing! :)

**Comment by kishan2612** [comment]
> Can somebody pretty please show me the way of passing ScopedModel between screens ? I'd prefer not to wrap my whole application, but to pass it somehow...
> 
> What I want to achieve is to create ScopedModel object in my ScreenTabs Widget, then pass it to tab ScreenBook (1st descendant) and then my tab navigates to another screen ScreenBookDetails (2nd descendant) -thats where I'm getting Error: Could not find correct ScopedModel.
> 
> `
> SCREEN TAB
> ...
> 
> ```
> class ScreenTabsState extends State<ScreenTabs> {
> ModelTabs modelTabs = ModelTabs(); //new Model object
> var screens = [new ScreenHome(),new ScreenBook(),];
> 
> @override
> Widget build(BuildContext context) {
> return ScopedModel<ModelTabs>(
> model: modelTabs, 
> child: Scaffold(...)
> body: Builder (builder: (context) => Container(child:  
> screens.elementAt(selectedIndex),)),
> bottomNavigationBar: BottomNavigationBar(
> currentIndex: selectedIndex,
> items: [...],
> onTap: onTabTapped,
> ),)...}`
> ```
> 
> `SCREEN BOOK //works fine
> 
> ```
> ...
> class ScreenBookState extends State<ScreenBook> {
> 
> @override
> Widget build(BuildContext context) {
> return new Scaffold(
> body: ScopedModelDescendant<ModelTabs>(builder: (context, child, model) {
> print(TAG + "model status:" +  model.status.toString());
> return model.status == Status.LOADING ? MyCircularProgressIndicator() :         
> Builder (builder: (context) => 
> Card(...
> child: InkWell(
> onTap: (){
> Navigator.of(context).pushNamed("/ScreenBookDetails");},))}}
> ```
> 
> `
> 
> `SCREEN BOOK DETAILS //error when printing
> 
> ```
> ...
> class ScreenBookDetailsState extends State<ScreenBookDetails>{
> 
> @override
> Widget build(BuildContext context) {
> return Scaffold(
> body: ScopedModelDescendant<ModelTabs>(builder: (context, child, model) {
> print(TAG + "scoped model status: " + model.status.toString()); //Error: Could not find the correct ScopedModel.
> return model.status == Status.LOADING ? MyCircularProgressIndicator() :     Builder(builder: (context) => Column(...)
> ```
> 
> ...
> `
> 
> Thank you very much in advance - I'm new to this stuff but the whole idea of ScopedModel is amazing! :)

You cant pass scoped model to different screen. You can access the scoped model only by its descendants. You have two options in your scenario. Create scoped model for each screen if the app is   big or wrap the app with common scoped model.
