### ISSUE TITLE
initial data not loading

### ISSUE THREAD

**Issue by tomosullivan8** [brianegan/scoped_model#78]
Hi

I've used ScopedModel for my app, and it works fine except for the initState reading of the data.
I've got data from a sqflite which i used to read the initial list of items.

This is how I have implemented it into the Model, but nothing is read initially (it funnily enough appears after I hit the floating action button and get taken to a AlertDialog):

```
Future readNoDoList() async {
    List items = await db.getItems();
    items.forEach((item) => itemList.add(NoDoItem.map(item)));
    notifyListeners();
  }
```

If I run the following code and apply to my initState the data appears:
```
Future readNoDoList() async {
    List items = await db.getItems();
    items.forEach((item) {
      setState(() {
        _model.itemList.add(NoDoItem.map(item));
      });
    });
  }
```
Ideally i'd rather read the data from the Model, is there anyway around this?

Thanks

**Comment by kishan2612** [comment]
> Hi
> 
> I've used ScopedModel for my app, and it works fine except for the initState reading of the data.
> I've got data from a sqflite which i used to read the initial list of items.
> 
> This is how I have implemented it into the Model, but nothing is read initially (it funnily enough appears after I hit the floating action button and get taken to a AlertDialog):
> 
> ```
> Future readNoDoList() async {
>     List items = await db.getItems();
>     items.forEach((item) => itemList.add(NoDoItem.map(item)));
>     notifyListeners();
>   }
> ```
> 
> If I run the following code and apply to my initState the data appears:
> 
> ```
> Future readNoDoList() async {
>     List items = await db.getItems();
>     items.forEach((item) {
>       setState(() {
>         _model.itemList.add(NoDoItem.map(item));
>       });
>     });
>   }
> ```
> 
> Ideally i'd rather read the data from the Model, is there anyway around this?
> 
> Thanks

Dont use forEach inside Async. Use for/Future.forEach.
See this [stackOverFlow](https://stackoverflow.com/questions/42467663/async-await-in-list-foreach)
