### ISSUE TITLE
Error when using ScopedModelDescendant

### ISSUE THREAD

**Issue by desona0810** [brianegan/scoped_model#79]
Hello there,
I got the following error when i'm trying to use scoped_model by the function ScopedModelDescendant<my_model>();

I/flutter ( 6268): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6268): The following ScopedModelError was thrown building ScopedModelDescendant<ProductsModel>(dirty):
I/flutter ( 6268): Error: Could not find the correct ScopedModel.
I/flutter ( 6268):
I/flutter ( 6268): To fix, please:
I/flutter ( 6268):
I/flutter ( 6268):   * Provide types to ScopedModel<MyModel>
I/flutter ( 6268):   * Provide types to ScopedModelDescendant<MyModel>
I/flutter ( 6268):   * Provide types to ScopedModel.of<MyModel>()
I/flutter ( 6268):   * Always use package imports. Ex: `import 'package:my_app/my_model.dart';
I/flutter ( 6268):  etc ...

I will share you the code i used, it is simple and easy to follow.
[third_app_.zip](https://github.com/brianegan/scoped_model/files/3382504/third_app_.zip)

**Comment by brianegan** [comment]
Hey there -- it looks like you have a `ScopedModelDescendant` Widget but you haven't wrapped that underneath a `ScopedModel` Widget.

Please review the Usage example in the README and see if that helps: https://github.com/brianegan/scoped_model#usage

**Comment by desona0810** [comment]
Hello Brianegan,
It works fine after wrapped in ScopedModel.

i think the older version like 0.1.0 doesn't need to wrap ScopedModelDescendant  inside ScopedModel
