### ISSUE TITLE
Losing state on orientation change

### ISSUE THREAD

**Issue by andrewpmoore** [brianegan/scoped_model#8]
I'm trying to use the scoped model for a subPage, but when the screen is recreated on an orientation change the state is lost.

I've put together a simple gist : [here](https://gist.github.com/andrewpmoore/2a69fe144a065b927ec64f641e9452d4)

If I move the scoped model above the material app then the data persists.
I'd wanted to have page scoped state and app scoped state, but when I've got data for a specific page I'm not sure how to get this working. It's most likely an issue in my code as I'm new to flutter, but I think an example like this would be handy for others too.

**Comment by brianegan** [comment]
Hey @andrewpmoore. Every time the orientation changes, it's going to call the `build` function again. That means you are recreating the `new AppModel()` on every build (hot reload would do the same thing).

To fix the issue, you need to create and store the AppModel in a `State` object. Something like this:

```dart
class MyApp extends StatefulWidget {
  @override
  MyAppState createState() {
    return new MyAppState();
  }
}

class MyAppState extends State<MyApp> {
  AppModel appModel;
  
  @override
  void initState() {
    appModel = new AppModel();
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Counter Example',
      theme: ThemeData.dark(),
      home: new ScopedModel<AppModel>(
        model: appModel,
        child: new FirstScreen(),
      ),
    );
  }
}
```

**Comment by andrewpmoore** [comment]
That's perfect, thanks for that. It's working a treat now 👍

**Comment by brianegan** [comment]
Nice! I'll close this out for now, but feel free to open more issues if ya run into trouble
