### ISSUE TITLE
Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe 

### ISSUE THREAD

**Issue by pheromone** [brianegan/scoped_model#83]
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable. To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.

  @override
  Widget build(BuildContext context) {
    return ScopedModelDescendant<MainModel>(
      builder: (context, child, model) {
        return Scaffold(
              
.....

ScopedModel.of<MainModel>(context, rebuildOnChange: true)
              .setUDID(udid);

**Comment by kishan2612** [comment]
@pheromone Looks lke context of the widget is gone. Check whether you are disposing the context before setUDID
