### ISSUE TITLE
Always losing state when hot reload AND hot restart

### ISSUE THREAD

**Issue by fliermanrw** [brianegan/scoped_model#85]
A kind of weird issue, because there is no real (relevant) error message available for this one as far as I'm aware of...

My problem is that everytime when an app is hot reloaded or hot restarted, there are dozens of error messages because the model hasn't got its data anymore. I have experienced this before when hot reloading, but wasn't a big problem because hot restart did work. Never been a problem untill now. The only option is do quit running and start running the app again.

- hot reload does change design items, but loses the model

Hope this isn't too vague. I can post flutter doctor -v of course, but that returns all fine...

Does anyone know what changed? (@brianegan perhaps...) Thank you

**Comment by kishan2612** [comment]
@fliermanrw  Paste some code from your scoped model and View attached to it

**Comment by fliermanrw** [comment]
Turns out I had to reinstall my AVD's. Still losing state with hot reload, but it does update te views so I guess that's acceptable. Closed.

**Comment by talksik** [comment]
same problem. just a pain that I have to force hot restart instead of hot reload whenever I make a change
