### ISSUE TITLE
ScopedModel  must  init  in  MyApp  function  bulid？

### ISSUE THREAD

**Issue by jjjjbababy** [brianegan/scoped_model#88]
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    HomeDataModel model = new HomeDataModel();
    return ScopedModel<HomeDataModel>(
      model: model,
      child: OKToast(
        child: MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.red,
          ),
          home: LoginPage(),
//      home: MyHomePage(title: 'Flutter Demo Home Page'),
        ),
      ),
    );
  }
}

but i have  many  models

**Comment by brianegan** [comment]
Hey there -- you generally don't want to create the `model` in the build function, but rather in the `main` function or in `initState` of a `State` class. That way the model will not be recreated every time the Widget is rebuilt!
