### ISSUE TITLE
ScopedModelDescendant

### ISSUE THREAD

**Issue by umidshox99** [brianegan/scoped_model#91]
return ScopedModelDescendant<AppStateModel>(
      builder: (context, child, model) => GestureDetector(
        onTap: () {
          model.setCategory(category);
          if (onCategoryTap != null) {
            onCategoryTap();
          }
        },
        child: model.selectedCategory == category
            ? Column(
                children: <Widget>[
                  const SizedBox(height: 16.0),
                  Text(
                    categoryString,
                    style: theme.textTheme.body2,
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 14.0),
                  Container(
                    width: 70.0,
                    height: 2.0,
                    color: kShrinePink400,
                  ),
                ],
              )
            : Padding(
                padding: const EdgeInsets.symmetric(vertical: 16.0),
                child: Text(
                  categoryString,
                  style: theme.textTheme.body2
                      .copyWith(color: kShrineBrown900.withAlpha(153)),
                  textAlign: TextAlign.center,
                ),
              ),
      ),
    );

**Comment by brianegan** [comment]
Hey there -- not quite sure how to help here -- are you receiving an error of some kind? In general, you need to provide type information to `ScopedModelDescendant` so it can find the right thing. The first line should probably be:

`ScopedModelDescendant<YourModelClassName>(`
